# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-05 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_activation_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activated_key',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
